package com.yunmu.core.model.source;

import java.io.Serializable;

public class OrderSource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_order_source.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_order_source.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_order_source.temp
     *
     * @mbggenerated
     */
    private String temp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yunmu_order_source
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_order_source.id
     *
     * @return the value of yunmu_order_source.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_order_source.id
     *
     * @param id the value for yunmu_order_source.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_order_source.name
     *
     * @return the value of yunmu_order_source.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_order_source.name
     *
     * @param name the value for yunmu_order_source.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_order_source.temp
     *
     * @return the value of yunmu_order_source.temp
     *
     * @mbggenerated
     */
    public String getTemp() {
        return temp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_order_source.temp
     *
     * @param temp the value for yunmu_order_source.temp
     *
     * @mbggenerated
     */
    public void setTemp(String temp) {
        this.temp = temp == null ? null : temp.trim();
    }
}