package com.ouchen.core.dao.personnel;

import com.ouchen.core.model.personnel.Personnel;
import com.ouchen.core.model.personnel.PersonnelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonnelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    int countByExample(PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    int deleteByExample(PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    int insert(Personnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    int insertSelective(Personnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    List<Personnel> selectByExample(PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    Personnel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Personnel record, @Param("example") PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Personnel record, @Param("example") PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Personnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Personnel record);
}