package com.ouchen.core.dao.hourse;

import com.ouchen.core.model.hourse.HourseType;
import com.ouchen.core.model.hourse.HourseTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HourseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_hourse_type
     *
     * @mbggenerated
     */
    int countByExample(HourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_hourse_type
     *
     * @mbggenerated
     */
    int deleteByExample(HourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_hourse_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_hourse_type
     *
     * @mbggenerated
     */
    int insert(HourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_hourse_type
     *
     * @mbggenerated
     */
    int insertSelective(HourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_hourse_type
     *
     * @mbggenerated
     */
    List<HourseType> selectByExample(HourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_hourse_type
     *
     * @mbggenerated
     */
    HourseType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_hourse_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HourseType record, @Param("example") HourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_hourse_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HourseType record, @Param("example") HourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_hourse_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_hourse_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HourseType record);
}