package com.ouchen.core.model.owner;

import java.io.Serializable;
import java.util.Date;

public class Owner implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_owner.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_owner.project_id
     *
     * @mbggenerated
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_owner.owner_name
     *
     * @mbggenerated
     */
    private String ownerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_owner.owner_pwd
     *
     * @mbggenerated
     */
    private String ownerPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_owner.owner_tel
     *
     * @mbggenerated
     */
    private String ownerTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_owner.owner_addr
     *
     * @mbggenerated
     */
    private String ownerAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_owner.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_owner.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_owner.owner_email
     *
     * @mbggenerated
     */
    private String ownerEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_owner.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_owner.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yunmu_owner
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_owner.id
     *
     * @return the value of yunmu_owner.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_owner.id
     *
     * @param id the value for yunmu_owner.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_owner.project_id
     *
     * @return the value of yunmu_owner.project_id
     *
     * @mbggenerated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_owner.project_id
     *
     * @param projectId the value for yunmu_owner.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_owner.owner_name
     *
     * @return the value of yunmu_owner.owner_name
     *
     * @mbggenerated
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_owner.owner_name
     *
     * @param ownerName the value for yunmu_owner.owner_name
     *
     * @mbggenerated
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_owner.owner_pwd
     *
     * @return the value of yunmu_owner.owner_pwd
     *
     * @mbggenerated
     */
    public String getOwnerPwd() {
        return ownerPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_owner.owner_pwd
     *
     * @param ownerPwd the value for yunmu_owner.owner_pwd
     *
     * @mbggenerated
     */
    public void setOwnerPwd(String ownerPwd) {
        this.ownerPwd = ownerPwd == null ? null : ownerPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_owner.owner_tel
     *
     * @return the value of yunmu_owner.owner_tel
     *
     * @mbggenerated
     */
    public String getOwnerTel() {
        return ownerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_owner.owner_tel
     *
     * @param ownerTel the value for yunmu_owner.owner_tel
     *
     * @mbggenerated
     */
    public void setOwnerTel(String ownerTel) {
        this.ownerTel = ownerTel == null ? null : ownerTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_owner.owner_addr
     *
     * @return the value of yunmu_owner.owner_addr
     *
     * @mbggenerated
     */
    public String getOwnerAddr() {
        return ownerAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_owner.owner_addr
     *
     * @param ownerAddr the value for yunmu_owner.owner_addr
     *
     * @mbggenerated
     */
    public void setOwnerAddr(String ownerAddr) {
        this.ownerAddr = ownerAddr == null ? null : ownerAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_owner.create_by
     *
     * @return the value of yunmu_owner.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_owner.create_by
     *
     * @param createBy the value for yunmu_owner.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_owner.token
     *
     * @return the value of yunmu_owner.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_owner.token
     *
     * @param token the value for yunmu_owner.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_owner.owner_email
     *
     * @return the value of yunmu_owner.owner_email
     *
     * @mbggenerated
     */
    public String getOwnerEmail() {
        return ownerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_owner.owner_email
     *
     * @param ownerEmail the value for yunmu_owner.owner_email
     *
     * @mbggenerated
     */
    public void setOwnerEmail(String ownerEmail) {
        this.ownerEmail = ownerEmail == null ? null : ownerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_owner.status
     *
     * @return the value of yunmu_owner.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_owner.status
     *
     * @param status the value for yunmu_owner.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_owner.create_time
     *
     * @return the value of yunmu_owner.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_owner.create_time
     *
     * @param createTime the value for yunmu_owner.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}