package com.yunmu.core.model.personnel;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PersonnelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    public PersonnelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeIsNull() {
            addCriterion("company_code is null");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeIsNotNull() {
            addCriterion("company_code is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeEqualTo(String value) {
            addCriterion("company_code =", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeNotEqualTo(String value) {
            addCriterion("company_code <>", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeGreaterThan(String value) {
            addCriterion("company_code >", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("company_code >=", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeLessThan(String value) {
            addCriterion("company_code <", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeLessThanOrEqualTo(String value) {
            addCriterion("company_code <=", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeLike(String value) {
            addCriterion("company_code like", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeNotLike(String value) {
            addCriterion("company_code not like", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeIn(List<String> values) {
            addCriterion("company_code in", values, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeNotIn(List<String> values) {
            addCriterion("company_code not in", values, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeBetween(String value1, String value2) {
            addCriterion("company_code between", value1, value2, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeNotBetween(String value1, String value2) {
            addCriterion("company_code not between", value1, value2, "companyCode");
            return (Criteria) this;
        }

        public Criteria andPersonnelNameIsNull() {
            addCriterion("personnel_name is null");
            return (Criteria) this;
        }

        public Criteria andPersonnelNameIsNotNull() {
            addCriterion("personnel_name is not null");
            return (Criteria) this;
        }

        public Criteria andPersonnelNameEqualTo(String value) {
            addCriterion("personnel_name =", value, "personnelName");
            return (Criteria) this;
        }

        public Criteria andPersonnelNameNotEqualTo(String value) {
            addCriterion("personnel_name <>", value, "personnelName");
            return (Criteria) this;
        }

        public Criteria andPersonnelNameGreaterThan(String value) {
            addCriterion("personnel_name >", value, "personnelName");
            return (Criteria) this;
        }

        public Criteria andPersonnelNameGreaterThanOrEqualTo(String value) {
            addCriterion("personnel_name >=", value, "personnelName");
            return (Criteria) this;
        }

        public Criteria andPersonnelNameLessThan(String value) {
            addCriterion("personnel_name <", value, "personnelName");
            return (Criteria) this;
        }

        public Criteria andPersonnelNameLessThanOrEqualTo(String value) {
            addCriterion("personnel_name <=", value, "personnelName");
            return (Criteria) this;
        }

        public Criteria andPersonnelNameLike(String value) {
            addCriterion("personnel_name like", value, "personnelName");
            return (Criteria) this;
        }

        public Criteria andPersonnelNameNotLike(String value) {
            addCriterion("personnel_name not like", value, "personnelName");
            return (Criteria) this;
        }

        public Criteria andPersonnelNameIn(List<String> values) {
            addCriterion("personnel_name in", values, "personnelName");
            return (Criteria) this;
        }

        public Criteria andPersonnelNameNotIn(List<String> values) {
            addCriterion("personnel_name not in", values, "personnelName");
            return (Criteria) this;
        }

        public Criteria andPersonnelNameBetween(String value1, String value2) {
            addCriterion("personnel_name between", value1, value2, "personnelName");
            return (Criteria) this;
        }

        public Criteria andPersonnelNameNotBetween(String value1, String value2) {
            addCriterion("personnel_name not between", value1, value2, "personnelName");
            return (Criteria) this;
        }

        public Criteria andPersonnelAgeIsNull() {
            addCriterion("personnel_age is null");
            return (Criteria) this;
        }

        public Criteria andPersonnelAgeIsNotNull() {
            addCriterion("personnel_age is not null");
            return (Criteria) this;
        }

        public Criteria andPersonnelAgeEqualTo(Integer value) {
            addCriterion("personnel_age =", value, "personnelAge");
            return (Criteria) this;
        }

        public Criteria andPersonnelAgeNotEqualTo(Integer value) {
            addCriterion("personnel_age <>", value, "personnelAge");
            return (Criteria) this;
        }

        public Criteria andPersonnelAgeGreaterThan(Integer value) {
            addCriterion("personnel_age >", value, "personnelAge");
            return (Criteria) this;
        }

        public Criteria andPersonnelAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("personnel_age >=", value, "personnelAge");
            return (Criteria) this;
        }

        public Criteria andPersonnelAgeLessThan(Integer value) {
            addCriterion("personnel_age <", value, "personnelAge");
            return (Criteria) this;
        }

        public Criteria andPersonnelAgeLessThanOrEqualTo(Integer value) {
            addCriterion("personnel_age <=", value, "personnelAge");
            return (Criteria) this;
        }

        public Criteria andPersonnelAgeIn(List<Integer> values) {
            addCriterion("personnel_age in", values, "personnelAge");
            return (Criteria) this;
        }

        public Criteria andPersonnelAgeNotIn(List<Integer> values) {
            addCriterion("personnel_age not in", values, "personnelAge");
            return (Criteria) this;
        }

        public Criteria andPersonnelAgeBetween(Integer value1, Integer value2) {
            addCriterion("personnel_age between", value1, value2, "personnelAge");
            return (Criteria) this;
        }

        public Criteria andPersonnelAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("personnel_age not between", value1, value2, "personnelAge");
            return (Criteria) this;
        }

        public Criteria andPersonnelSexIsNull() {
            addCriterion("personnel_sex is null");
            return (Criteria) this;
        }

        public Criteria andPersonnelSexIsNotNull() {
            addCriterion("personnel_sex is not null");
            return (Criteria) this;
        }

        public Criteria andPersonnelSexEqualTo(Integer value) {
            addCriterion("personnel_sex =", value, "personnelSex");
            return (Criteria) this;
        }

        public Criteria andPersonnelSexNotEqualTo(Integer value) {
            addCriterion("personnel_sex <>", value, "personnelSex");
            return (Criteria) this;
        }

        public Criteria andPersonnelSexGreaterThan(Integer value) {
            addCriterion("personnel_sex >", value, "personnelSex");
            return (Criteria) this;
        }

        public Criteria andPersonnelSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("personnel_sex >=", value, "personnelSex");
            return (Criteria) this;
        }

        public Criteria andPersonnelSexLessThan(Integer value) {
            addCriterion("personnel_sex <", value, "personnelSex");
            return (Criteria) this;
        }

        public Criteria andPersonnelSexLessThanOrEqualTo(Integer value) {
            addCriterion("personnel_sex <=", value, "personnelSex");
            return (Criteria) this;
        }

        public Criteria andPersonnelSexIn(List<Integer> values) {
            addCriterion("personnel_sex in", values, "personnelSex");
            return (Criteria) this;
        }

        public Criteria andPersonnelSexNotIn(List<Integer> values) {
            addCriterion("personnel_sex not in", values, "personnelSex");
            return (Criteria) this;
        }

        public Criteria andPersonnelSexBetween(Integer value1, Integer value2) {
            addCriterion("personnel_sex between", value1, value2, "personnelSex");
            return (Criteria) this;
        }

        public Criteria andPersonnelSexNotBetween(Integer value1, Integer value2) {
            addCriterion("personnel_sex not between", value1, value2, "personnelSex");
            return (Criteria) this;
        }

        public Criteria andPersonnelIdCardIsNull() {
            addCriterion("personnel_id_card is null");
            return (Criteria) this;
        }

        public Criteria andPersonnelIdCardIsNotNull() {
            addCriterion("personnel_id_card is not null");
            return (Criteria) this;
        }

        public Criteria andPersonnelIdCardEqualTo(String value) {
            addCriterion("personnel_id_card =", value, "personnelIdCard");
            return (Criteria) this;
        }

        public Criteria andPersonnelIdCardNotEqualTo(String value) {
            addCriterion("personnel_id_card <>", value, "personnelIdCard");
            return (Criteria) this;
        }

        public Criteria andPersonnelIdCardGreaterThan(String value) {
            addCriterion("personnel_id_card >", value, "personnelIdCard");
            return (Criteria) this;
        }

        public Criteria andPersonnelIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("personnel_id_card >=", value, "personnelIdCard");
            return (Criteria) this;
        }

        public Criteria andPersonnelIdCardLessThan(String value) {
            addCriterion("personnel_id_card <", value, "personnelIdCard");
            return (Criteria) this;
        }

        public Criteria andPersonnelIdCardLessThanOrEqualTo(String value) {
            addCriterion("personnel_id_card <=", value, "personnelIdCard");
            return (Criteria) this;
        }

        public Criteria andPersonnelIdCardLike(String value) {
            addCriterion("personnel_id_card like", value, "personnelIdCard");
            return (Criteria) this;
        }

        public Criteria andPersonnelIdCardNotLike(String value) {
            addCriterion("personnel_id_card not like", value, "personnelIdCard");
            return (Criteria) this;
        }

        public Criteria andPersonnelIdCardIn(List<String> values) {
            addCriterion("personnel_id_card in", values, "personnelIdCard");
            return (Criteria) this;
        }

        public Criteria andPersonnelIdCardNotIn(List<String> values) {
            addCriterion("personnel_id_card not in", values, "personnelIdCard");
            return (Criteria) this;
        }

        public Criteria andPersonnelIdCardBetween(String value1, String value2) {
            addCriterion("personnel_id_card between", value1, value2, "personnelIdCard");
            return (Criteria) this;
        }

        public Criteria andPersonnelIdCardNotBetween(String value1, String value2) {
            addCriterion("personnel_id_card not between", value1, value2, "personnelIdCard");
            return (Criteria) this;
        }

        public Criteria andPersonnelTelIsNull() {
            addCriterion("personnel_tel is null");
            return (Criteria) this;
        }

        public Criteria andPersonnelTelIsNotNull() {
            addCriterion("personnel_tel is not null");
            return (Criteria) this;
        }

        public Criteria andPersonnelTelEqualTo(String value) {
            addCriterion("personnel_tel =", value, "personnelTel");
            return (Criteria) this;
        }

        public Criteria andPersonnelTelNotEqualTo(String value) {
            addCriterion("personnel_tel <>", value, "personnelTel");
            return (Criteria) this;
        }

        public Criteria andPersonnelTelGreaterThan(String value) {
            addCriterion("personnel_tel >", value, "personnelTel");
            return (Criteria) this;
        }

        public Criteria andPersonnelTelGreaterThanOrEqualTo(String value) {
            addCriterion("personnel_tel >=", value, "personnelTel");
            return (Criteria) this;
        }

        public Criteria andPersonnelTelLessThan(String value) {
            addCriterion("personnel_tel <", value, "personnelTel");
            return (Criteria) this;
        }

        public Criteria andPersonnelTelLessThanOrEqualTo(String value) {
            addCriterion("personnel_tel <=", value, "personnelTel");
            return (Criteria) this;
        }

        public Criteria andPersonnelTelLike(String value) {
            addCriterion("personnel_tel like", value, "personnelTel");
            return (Criteria) this;
        }

        public Criteria andPersonnelTelNotLike(String value) {
            addCriterion("personnel_tel not like", value, "personnelTel");
            return (Criteria) this;
        }

        public Criteria andPersonnelTelIn(List<String> values) {
            addCriterion("personnel_tel in", values, "personnelTel");
            return (Criteria) this;
        }

        public Criteria andPersonnelTelNotIn(List<String> values) {
            addCriterion("personnel_tel not in", values, "personnelTel");
            return (Criteria) this;
        }

        public Criteria andPersonnelTelBetween(String value1, String value2) {
            addCriterion("personnel_tel between", value1, value2, "personnelTel");
            return (Criteria) this;
        }

        public Criteria andPersonnelTelNotBetween(String value1, String value2) {
            addCriterion("personnel_tel not between", value1, value2, "personnelTel");
            return (Criteria) this;
        }

        public Criteria andPersonnelEmailIsNull() {
            addCriterion("personnel_email is null");
            return (Criteria) this;
        }

        public Criteria andPersonnelEmailIsNotNull() {
            addCriterion("personnel_email is not null");
            return (Criteria) this;
        }

        public Criteria andPersonnelEmailEqualTo(String value) {
            addCriterion("personnel_email =", value, "personnelEmail");
            return (Criteria) this;
        }

        public Criteria andPersonnelEmailNotEqualTo(String value) {
            addCriterion("personnel_email <>", value, "personnelEmail");
            return (Criteria) this;
        }

        public Criteria andPersonnelEmailGreaterThan(String value) {
            addCriterion("personnel_email >", value, "personnelEmail");
            return (Criteria) this;
        }

        public Criteria andPersonnelEmailGreaterThanOrEqualTo(String value) {
            addCriterion("personnel_email >=", value, "personnelEmail");
            return (Criteria) this;
        }

        public Criteria andPersonnelEmailLessThan(String value) {
            addCriterion("personnel_email <", value, "personnelEmail");
            return (Criteria) this;
        }

        public Criteria andPersonnelEmailLessThanOrEqualTo(String value) {
            addCriterion("personnel_email <=", value, "personnelEmail");
            return (Criteria) this;
        }

        public Criteria andPersonnelEmailLike(String value) {
            addCriterion("personnel_email like", value, "personnelEmail");
            return (Criteria) this;
        }

        public Criteria andPersonnelEmailNotLike(String value) {
            addCriterion("personnel_email not like", value, "personnelEmail");
            return (Criteria) this;
        }

        public Criteria andPersonnelEmailIn(List<String> values) {
            addCriterion("personnel_email in", values, "personnelEmail");
            return (Criteria) this;
        }

        public Criteria andPersonnelEmailNotIn(List<String> values) {
            addCriterion("personnel_email not in", values, "personnelEmail");
            return (Criteria) this;
        }

        public Criteria andPersonnelEmailBetween(String value1, String value2) {
            addCriterion("personnel_email between", value1, value2, "personnelEmail");
            return (Criteria) this;
        }

        public Criteria andPersonnelEmailNotBetween(String value1, String value2) {
            addCriterion("personnel_email not between", value1, value2, "personnelEmail");
            return (Criteria) this;
        }

        public Criteria andPersonnelAddrIsNull() {
            addCriterion("personnel_addr is null");
            return (Criteria) this;
        }

        public Criteria andPersonnelAddrIsNotNull() {
            addCriterion("personnel_addr is not null");
            return (Criteria) this;
        }

        public Criteria andPersonnelAddrEqualTo(String value) {
            addCriterion("personnel_addr =", value, "personnelAddr");
            return (Criteria) this;
        }

        public Criteria andPersonnelAddrNotEqualTo(String value) {
            addCriterion("personnel_addr <>", value, "personnelAddr");
            return (Criteria) this;
        }

        public Criteria andPersonnelAddrGreaterThan(String value) {
            addCriterion("personnel_addr >", value, "personnelAddr");
            return (Criteria) this;
        }

        public Criteria andPersonnelAddrGreaterThanOrEqualTo(String value) {
            addCriterion("personnel_addr >=", value, "personnelAddr");
            return (Criteria) this;
        }

        public Criteria andPersonnelAddrLessThan(String value) {
            addCriterion("personnel_addr <", value, "personnelAddr");
            return (Criteria) this;
        }

        public Criteria andPersonnelAddrLessThanOrEqualTo(String value) {
            addCriterion("personnel_addr <=", value, "personnelAddr");
            return (Criteria) this;
        }

        public Criteria andPersonnelAddrLike(String value) {
            addCriterion("personnel_addr like", value, "personnelAddr");
            return (Criteria) this;
        }

        public Criteria andPersonnelAddrNotLike(String value) {
            addCriterion("personnel_addr not like", value, "personnelAddr");
            return (Criteria) this;
        }

        public Criteria andPersonnelAddrIn(List<String> values) {
            addCriterion("personnel_addr in", values, "personnelAddr");
            return (Criteria) this;
        }

        public Criteria andPersonnelAddrNotIn(List<String> values) {
            addCriterion("personnel_addr not in", values, "personnelAddr");
            return (Criteria) this;
        }

        public Criteria andPersonnelAddrBetween(String value1, String value2) {
            addCriterion("personnel_addr between", value1, value2, "personnelAddr");
            return (Criteria) this;
        }

        public Criteria andPersonnelAddrNotBetween(String value1, String value2) {
            addCriterion("personnel_addr not between", value1, value2, "personnelAddr");
            return (Criteria) this;
        }

        public Criteria andPersonnelStatusIsNull() {
            addCriterion("personnel_status is null");
            return (Criteria) this;
        }

        public Criteria andPersonnelStatusIsNotNull() {
            addCriterion("personnel_status is not null");
            return (Criteria) this;
        }

        public Criteria andPersonnelStatusEqualTo(Integer value) {
            addCriterion("personnel_status =", value, "personnelStatus");
            return (Criteria) this;
        }

        public Criteria andPersonnelStatusNotEqualTo(Integer value) {
            addCriterion("personnel_status <>", value, "personnelStatus");
            return (Criteria) this;
        }

        public Criteria andPersonnelStatusGreaterThan(Integer value) {
            addCriterion("personnel_status >", value, "personnelStatus");
            return (Criteria) this;
        }

        public Criteria andPersonnelStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("personnel_status >=", value, "personnelStatus");
            return (Criteria) this;
        }

        public Criteria andPersonnelStatusLessThan(Integer value) {
            addCriterion("personnel_status <", value, "personnelStatus");
            return (Criteria) this;
        }

        public Criteria andPersonnelStatusLessThanOrEqualTo(Integer value) {
            addCriterion("personnel_status <=", value, "personnelStatus");
            return (Criteria) this;
        }

        public Criteria andPersonnelStatusIn(List<Integer> values) {
            addCriterion("personnel_status in", values, "personnelStatus");
            return (Criteria) this;
        }

        public Criteria andPersonnelStatusNotIn(List<Integer> values) {
            addCriterion("personnel_status not in", values, "personnelStatus");
            return (Criteria) this;
        }

        public Criteria andPersonnelStatusBetween(Integer value1, Integer value2) {
            addCriterion("personnel_status between", value1, value2, "personnelStatus");
            return (Criteria) this;
        }

        public Criteria andPersonnelStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("personnel_status not between", value1, value2, "personnelStatus");
            return (Criteria) this;
        }

        public Criteria andJoinedDateIsNull() {
            addCriterion("joined_date is null");
            return (Criteria) this;
        }

        public Criteria andJoinedDateIsNotNull() {
            addCriterion("joined_date is not null");
            return (Criteria) this;
        }

        public Criteria andJoinedDateEqualTo(Date value) {
            addCriterion("joined_date =", value, "joinedDate");
            return (Criteria) this;
        }

        public Criteria andJoinedDateNotEqualTo(Date value) {
            addCriterion("joined_date <>", value, "joinedDate");
            return (Criteria) this;
        }

        public Criteria andJoinedDateGreaterThan(Date value) {
            addCriterion("joined_date >", value, "joinedDate");
            return (Criteria) this;
        }

        public Criteria andJoinedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("joined_date >=", value, "joinedDate");
            return (Criteria) this;
        }

        public Criteria andJoinedDateLessThan(Date value) {
            addCriterion("joined_date <", value, "joinedDate");
            return (Criteria) this;
        }

        public Criteria andJoinedDateLessThanOrEqualTo(Date value) {
            addCriterion("joined_date <=", value, "joinedDate");
            return (Criteria) this;
        }

        public Criteria andJoinedDateIn(List<Date> values) {
            addCriterion("joined_date in", values, "joinedDate");
            return (Criteria) this;
        }

        public Criteria andJoinedDateNotIn(List<Date> values) {
            addCriterion("joined_date not in", values, "joinedDate");
            return (Criteria) this;
        }

        public Criteria andJoinedDateBetween(Date value1, Date value2) {
            addCriterion("joined_date between", value1, value2, "joinedDate");
            return (Criteria) this;
        }

        public Criteria andJoinedDateNotBetween(Date value1, Date value2) {
            addCriterion("joined_date not between", value1, value2, "joinedDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("create_by like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("create_by not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("update_by like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("update_by not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yunmu_personnel
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yunmu_personnel
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}